steps:
  # Étape 1: Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/somme-python-repo/somme-python:$COMMIT_SHA', '.']

  # Étape 2: Push de l'image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/somme-python-repo/somme-python:$COMMIT_SHA']

  # Étape 3: Déploiement sur GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=kubernetes/
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/somme-python-repo/somme-python:$COMMIT_SHA
      - --location=us-central1-a
      - --cluster=my-gke-cluster

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/somme-python-repo/somme-python:$COMMIT_SHA