steps:
  # Étape 1: Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/somme-python:$COMMIT_SHA', '.']

  # Étape 2: Push de l'image vers Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/somme-python:$COMMIT_SHA']

  # Étape 3: Déploiement sur GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=kubernetes/
      - --image=gcr.io/$PROJECT_ID/somme-python:$COMMIT_SHA
      - --location=us-central1-a
      - --cluster=my-gke-cluster

images:
  - 'gcr.io/$PROJECT_ID/somme-python:$COMMIT_SHA'
options:
  logging: 'NONE'