apiVersion: apps/v1
kind: Deployment
metadata:
  name: somme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: somme-app
  template:
    metadata:
      labels:
        app: somme-app
    spec:
      containers:
        - name: somme-container
          image: us-central1-docker.pkg.dev/$PROJECT_ID/somme-python-repo/somme-python:$COMMIT_SHA
          imagePullPolicy: Always
